root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  node: true
  es2022: true
parserOptions:
  sourceType: 'module'
  project: './tsconfig.eslint.json'
ignorePatterns:
  - 'dist'
extends:
  - 'airbnb-base'
  - 'airbnb-typescript/base'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
rules:
  'import/prefer-default-export': 'off'
  '@typescript-eslint/quotes':
    - 'error'
    - 'single'
